version: '3.7'

services:
  oriserver:
    image: jonwadeuk/oriserver:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      ORI_PORT: ${ORI_PORT}
    ports:
      - ${ORI_PORT}:${ORI_PORT}
    volumes:
      - ./:/app
