// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ori.proto

package ori

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SummationInput struct {
	First                int64    `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last                 int64    `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummationInput) Reset()         { *m = SummationInput{} }
func (m *SummationInput) String() string { return proto.CompactTextString(m) }
func (*SummationInput) ProtoMessage()    {}
func (*SummationInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_01698aa773ec568e, []int{0}
}

func (m *SummationInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummationInput.Unmarshal(m, b)
}
func (m *SummationInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummationInput.Marshal(b, m, deterministic)
}
func (m *SummationInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummationInput.Merge(m, src)
}
func (m *SummationInput) XXX_Size() int {
	return xxx_messageInfo_SummationInput.Size(m)
}
func (m *SummationInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SummationInput.DiscardUnknown(m)
}

var xxx_messageInfo_SummationInput proto.InternalMessageInfo

func (m *SummationInput) GetFirst() int64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *SummationInput) GetLast() int64 {
	if m != nil {
		return m.Last
	}
	return 0
}

type FactorialInput struct {
	Base                 int64    `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactorialInput) Reset()         { *m = FactorialInput{} }
func (m *FactorialInput) String() string { return proto.CompactTextString(m) }
func (*FactorialInput) ProtoMessage()    {}
func (*FactorialInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_01698aa773ec568e, []int{1}
}

func (m *FactorialInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactorialInput.Unmarshal(m, b)
}
func (m *FactorialInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactorialInput.Marshal(b, m, deterministic)
}
func (m *FactorialInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactorialInput.Merge(m, src)
}
func (m *FactorialInput) XXX_Size() int {
	return xxx_messageInfo_FactorialInput.Size(m)
}
func (m *FactorialInput) XXX_DiscardUnknown() {
	xxx_messageInfo_FactorialInput.DiscardUnknown(m)
}

var xxx_messageInfo_FactorialInput proto.InternalMessageInfo

func (m *FactorialInput) GetBase() int64 {
	if m != nil {
		return m.Base
	}
	return 0
}

type SummationResult struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	First                int64    `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	Last                 int64    `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummationResult) Reset()         { *m = SummationResult{} }
func (m *SummationResult) String() string { return proto.CompactTextString(m) }
func (*SummationResult) ProtoMessage()    {}
func (*SummationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_01698aa773ec568e, []int{2}
}

func (m *SummationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummationResult.Unmarshal(m, b)
}
func (m *SummationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummationResult.Marshal(b, m, deterministic)
}
func (m *SummationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummationResult.Merge(m, src)
}
func (m *SummationResult) XXX_Size() int {
	return xxx_messageInfo_SummationResult.Size(m)
}
func (m *SummationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SummationResult.DiscardUnknown(m)
}

var xxx_messageInfo_SummationResult proto.InternalMessageInfo

func (m *SummationResult) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SummationResult) GetFirst() int64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *SummationResult) GetLast() int64 {
	if m != nil {
		return m.Last
	}
	return 0
}

type FactorialResult struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Base                 int64    `protobuf:"varint,2,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FactorialResult) Reset()         { *m = FactorialResult{} }
func (m *FactorialResult) String() string { return proto.CompactTextString(m) }
func (*FactorialResult) ProtoMessage()    {}
func (*FactorialResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_01698aa773ec568e, []int{3}
}

func (m *FactorialResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FactorialResult.Unmarshal(m, b)
}
func (m *FactorialResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FactorialResult.Marshal(b, m, deterministic)
}
func (m *FactorialResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FactorialResult.Merge(m, src)
}
func (m *FactorialResult) XXX_Size() int {
	return xxx_messageInfo_FactorialResult.Size(m)
}
func (m *FactorialResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FactorialResult.DiscardUnknown(m)
}

var xxx_messageInfo_FactorialResult proto.InternalMessageInfo

func (m *FactorialResult) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *FactorialResult) GetBase() int64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func init() {
	proto.RegisterType((*SummationInput)(nil), "SummationInput")
	proto.RegisterType((*FactorialInput)(nil), "FactorialInput")
	proto.RegisterType((*SummationResult)(nil), "SummationResult")
	proto.RegisterType((*FactorialResult)(nil), "FactorialResult")
}

func init() { proto.RegisterFile("ori.proto", fileDescriptor_01698aa773ec568e) }

var fileDescriptor_01698aa773ec568e = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2f, 0xca, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe2, 0xe2, 0x0b, 0x2e, 0xcd, 0xcd, 0x4d, 0x2c, 0xc9,
	0xcc, 0xcf, 0xf3, 0xcc, 0x2b, 0x28, 0x2d, 0x11, 0x12, 0xe1, 0x62, 0x4d, 0xcb, 0x2c, 0x2a, 0x2e,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x72, 0x12, 0x8b,
	0x4b, 0x24, 0x98, 0xc0, 0x82, 0x60, 0xb6, 0x92, 0x0a, 0x17, 0x9f, 0x5b, 0x62, 0x72, 0x49, 0x7e,
	0x51, 0x66, 0x62, 0x0e, 0x44, 0xaf, 0x10, 0x17, 0x4b, 0x52, 0x62, 0x71, 0x2a, 0x54, 0x2b, 0x98,
	0xad, 0x14, 0xcc, 0xc5, 0x0f, 0xb7, 0x21, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x48, 0x8c, 0x8b,
	0xad, 0x08, 0xcc, 0x82, 0x2a, 0x84, 0xf2, 0x10, 0x56, 0x33, 0x61, 0xb3, 0x9a, 0x19, 0xc9, 0x6a,
	0x5b, 0x2e, 0x7e, 0xb8, 0xd5, 0x04, 0x0c, 0x85, 0xb9, 0x89, 0x09, 0xe1, 0x26, 0xa3, 0x02, 0x2e,
	0x2e, 0xdf, 0xc4, 0x92, 0x0c, 0x8f, 0xd4, 0x9c, 0x82, 0xd4, 0x22, 0x21, 0x03, 0x2e, 0x4e, 0xb8,
	0x0b, 0x85, 0xf8, 0xf5, 0x50, 0xc3, 0x43, 0x4a, 0x40, 0x0f, 0xcd, 0xf9, 0x4a, 0x0c, 0x20, 0x1d,
	0x70, 0xeb, 0x85, 0xf8, 0xf5, 0x50, 0x43, 0x41, 0x4a, 0x40, 0x0f, 0xcd, 0x6d, 0x4a, 0x0c, 0x49,
	0x6c, 0xe0, 0xe0, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x19, 0x53, 0xba, 0x7b, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MathHelperClient is the client API for MathHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathHelperClient interface {
	Summation(ctx context.Context, in *SummationInput, opts ...grpc.CallOption) (*SummationResult, error)
	Factorial(ctx context.Context, in *FactorialInput, opts ...grpc.CallOption) (*FactorialResult, error)
}

type mathHelperClient struct {
	cc *grpc.ClientConn
}

func NewMathHelperClient(cc *grpc.ClientConn) MathHelperClient {
	return &mathHelperClient{cc}
}

func (c *mathHelperClient) Summation(ctx context.Context, in *SummationInput, opts ...grpc.CallOption) (*SummationResult, error) {
	out := new(SummationResult)
	err := c.cc.Invoke(ctx, "/MathHelper/Summation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathHelperClient) Factorial(ctx context.Context, in *FactorialInput, opts ...grpc.CallOption) (*FactorialResult, error) {
	out := new(FactorialResult)
	err := c.cc.Invoke(ctx, "/MathHelper/Factorial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathHelperServer is the server API for MathHelper service.
type MathHelperServer interface {
	Summation(context.Context, *SummationInput) (*SummationResult, error)
	Factorial(context.Context, *FactorialInput) (*FactorialResult, error)
}

// UnimplementedMathHelperServer can be embedded to have forward compatible implementations.
type UnimplementedMathHelperServer struct {
}

func (*UnimplementedMathHelperServer) Summation(ctx context.Context, req *SummationInput) (*SummationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Summation not implemented")
}
func (*UnimplementedMathHelperServer) Factorial(ctx context.Context, req *FactorialInput) (*FactorialResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Factorial not implemented")
}

func RegisterMathHelperServer(s *grpc.Server, srv MathHelperServer) {
	s.RegisterService(&_MathHelper_serviceDesc, srv)
}

func _MathHelper_Summation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathHelperServer).Summation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathHelper/Summation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathHelperServer).Summation(ctx, req.(*SummationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathHelper_Factorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactorialInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathHelperServer).Factorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MathHelper/Factorial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathHelperServer).Factorial(ctx, req.(*FactorialInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _MathHelper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MathHelper",
	HandlerType: (*MathHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Summation",
			Handler:    _MathHelper_Summation_Handler,
		},
		{
			MethodName: "Factorial",
			Handler:    _MathHelper_Factorial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ori.proto",
}
