apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: oriserver
    app: oriserver
  name: oriserver
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    io.kompose.service: oriserver
status:
  loadBalancer: {}
