apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: oriserver
    app: oriserver
  name: oriserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: oriserver
    spec:
      containers:
      - env:
        - name: ORI_PORT
          value: "50051"
        image: jonwadeuk/oriserver:latest
        name: oriserver
        ports:
        - containerPort: 50051
        resources: {}
      restartPolicy: Always
status: {}
